[project]
name = "extractor-marker"
version = "0.1.0"
dependencies = [
    "torch>=2.4.1",
    "torchvision>=0.19.1",
    "torchaudio>=2.4.1",
    "marker-pdf>=1.10.2",
    "surya-ocr>=0.17.1",
    "transformers>=4.56.1", # Kita ikutin kemauan Surya
    "weasyprint>=62.0",
    "pypdf>=5.0.0",
    "tqdm>=4.67.3",
    "python-dotenv>=1.2.2",
    "huggingface-hub>=0.28.0",
    "hf-transfer>=0.1.9",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu121" }
torchvision = { index = "pytorch-cu121" }
torchaudio = { index = "pytorch-cu121" }